name: AWS ScoutSuite Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pipx and ScoutSuite
      run: |
        sudo apt update
        sudo apt install -y pipx
        pipx install scoutsuite
        echo 'export PATH=$PATH:/usr/local/bin' >> $GITHUB_ENV

    - name: Configure AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Run ScoutSuite scan
      run: |
        scoutsuite scan --no-browser --report-dir report --provider aws

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: scoutsuite-report
        path: report
